Repository tinkerbell/smee, pull requests merged in 2020-07, with the labels that each got.

#44 Cleanup after new data model
  go.mod
  installers/vmware/ipxe_script_test.go
  ipxe/settings.go
  job/dhcp.go
  job/dhcp_test.go
  job/events.go
  job/events_test.go
  job/fetch.go
  job/hardware.go
  job/helpers.go
  job/job.go
  job/job_test.go
  job/mock.go
  job/network.go
  packet/client.go
  packet/endpoints.go
  packet/models.go
  packet/models_cacher.go
  packet/models_test.go
  packet/models_tinkerbell.go
  packet/util.go
Labels: ready-to-merge

#57 Production into master
  installers/osie/main.go
  installers/osie/mirror.go
  job/dhcp.go
  job/helpers.go
  job/mock.go
  packet/models.go
  packet/models_cacher.go
  packet/models_test.go
  packet/models_tinkerbell.go
Labels: ready-to-merge

#56 Stricter data model version handling
  packet/endpoints.go
  packet/models.go
Labels: ready-to-merge

#59 Fix api discovery fetch
  go.mod
  go.sum
  packet/endpoints.go
  packet/endpoints_test.go
  packet/mock_cacher/cacher_mock.go
  shell.nix
Labels: ready-to-merge

#50 No pxe boot #35
  go.mod
  go.sum
  job/job.go
  job/job_test.go
  packet/client.go
  packet/endpoints.go
  packet/endpoints_test.go
  packet/mock_workflow/workflow_mock.go
Labels: enhancement, good first issue, ready-to-merge

#58 ENG-6658 user defined metadata
  go.mod
  go.sum
  packet/endpoints.go
Labels: P1, enhancement, size/S
