Repository tinkerbell/smee, pull requests merged in 2021-08, with the labels that each got.

#185 Back down to Alpine 3.13
  Dockerfile
Labels: ready-to-merge

#176 Add/update DCO, CoC, contributing ... files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: ready-to-merge

#192 support a more generic ipxe installer
  installers/custom_ipxe/errors.go
  installers/custom_ipxe/ipxe_script_test.go
  installers/custom_ipxe/main.go
  installers/custom_ipxe/main_test.go
  job/ipxe.go
  job/mock.go
  packet/models.go
Labels: ready-to-merge

#183 add opentelemetry
  cmd/boots/dhcp.go
  cmd/boots/dhcp_test.go
  cmd/boots/http.go
  cmd/boots/http_test.go
  cmd/boots/main.go
  cmd/boots/tftp.go
  cmd/boots/tftp_test.go
  docker-compose.yml
  go.mod
  go.sum
  installers/coreos/ignition.go
  installers/coreos/oem.go
  installers/http.go
  installers/vmware/kickstart-esxi.go
  installers/vmware/main.go
  job/dhcp.go
  job/events.go
  job/events_test.go
  job/fetch.go
  job/hardware.go
  job/http.go
  job/ipxe.go
  job/job.go
  job/job_test.go
  job/logging.go
  packet/client.go
  packet/endpoints.go
  packet/endpoints_test.go
  test/Dockerfile
  test/busybox-udhcpc-script.sh
  test/otel-collector.yaml
  test/standalone-hardware.json
  test/start-boots.sh
  test/test-boots.sh
Labels: ready-to-merge

#198 Drop bouk/monkey dependency
  Makefile
  cmd/boots/dhcp_test.go
  cmd/boots/tftp_test.go
  go.mod
  go.sum
  rules.mk
Labels: ready-to-merge

#184 Explicit installer registration
  cmd/boots/http.go
  cmd/boots/main.go
  cmd/boots/tftp.go
  installers/coreos/ignition.go
  installers/coreos/ipxe_script_test.go
  installers/coreos/main.go
  installers/coreos/oem.go
  installers/custom_ipxe/ipxe_script_test.go
  installers/custom_ipxe/main.go
  installers/custom_ipxe/main_test.go
  installers/http.go
  installers/nixos/ipxe_script_test.go
  installers/nixos/main.go
  installers/nixos/paths_test.go
  installers/osie/ipxe_script_test.go
  installers/osie/main.go
  installers/rancher/ipxe_script_test.go
  installers/rancher/main.go
  installers/vmware/ipxe_script_test.go
  installers/vmware/kickstart-esxi.go
  installers/vmware/main.go
  job/http.go
  job/ipxe.go
  job/job.go
Labels: kind/feature

#188 Add design philosophy doc:
  docs/DESIGNPHILOSOPHY.md
Labels: kind/documentation

#203 Fix panic: http: multiple registrations for /hardware-components:
  cmd/boots/http.go
Labels: kind/bug, priority/critical-urgent, kind/regression
